global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: query-exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'host.docker.internal:8080'
